version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080" # Map port 8080 on the host to port 80 in the container
    environment:
      - NODE_ENV=production